{"name": "Возникновение ошибки при пропуске поля логин для аутентификации", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nassert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 400}\n  Use -v to get more diff", "trace": "self = <tests.test_authorization_courier.TestCourierLogin object at 0x00000231A0672210>\nregister_new_courier = (<Response [201]>, {'firstName': 'gwjbgfvgus', 'login': 'ejnnotbthr', 'password': 'zupupgdbmn'}, 498808)\n\n    @allure.title('Возникновение ошибки при пропуске поля логин для аутентификации')\n    @allure.description('Генерация карточки курьера, попытка аутентификации без заполнения поля логин. Код ответа 400 Bad Request, тело ответа Недостаточно данных для входа')\n    def test_courier_login_empty_login(self, register_new_courier):\n        response, payload, courier_id = register_new_courier\n        login = ''\n        password = payload['password']\n    \n        payload = {\n            'login': login,\n            'password': password\n        }\n        response = requests.post(Urls.url_courier_login, data=payload)\n        assert response.status_code == 400, f\"Unexpected status code: {response.status_code}\"\n>       assert response.json() == {\n            'message': 'Недостаточно данных для входа'}, f\"Unexpected response: {response.json()}\"\nE       AssertionError: Unexpected response: {'code': 400, 'message': 'Недостаточно данных для входа'}\nE       assert {'code': 400,...ых для входа'} == {'message': '...ых для входа'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Left contains 1 more item:\nE         {'code': 400}\nE         Use -v to get more diff\n\ntests\\test_authorization_courier.py:40: AssertionError"}, "description": "Генерация карточки курьера, попытка аутентификации без заполнения поля логин. Код ответа 400 Bad Request, тело ответа Недостаточно данных для входа", "start": 1744123449520, "stop": 1744123449601, "uuid": "9a7855a3-80f1-48b0-b0fc-4053565b2a8f", "historyId": "791d2a56823522589ff7797d2fa07e1b", "testCaseId": "791d2a56823522589ff7797d2fa07e1b", "fullName": "tests.test_authorization_courier.TestCourierLogin#test_courier_login_empty_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "5896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}