{"name": "Получение ошибки при создании дубликата карточки", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 409, 'message': 'Этот логин уже используется. Попробуйте другой.'}\nassert {'code': 409,...уйте другой.'} == {'message': '...используется'}\n  \n  Differing items:\n  {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\n  Left contains 1 more item:\n  {'code': 409}\n  Use -v to get more diff", "trace": "self = <tests.test_courier_create.TestCourierCreate object at 0x000001CA8F66AD50>\nregister_new_courier = (<Response [201]>, {'firstName': 'javworovmy', 'login': 'znggmisuou', 'password': 'wugkzecwgl'}, 499582)\n\n    @allure.title('Получение ошибки при создании дубликата карточки')\n    @allure.description('Создание дубликата карточки. Код ответа 409 Сonflict. тело ответа Этот логин уже используется')\n    def test_create_courier_existing_login(self, register_new_courier):\n        response, payload, courier_id = register_new_courier\n        login = payload['login']\n    \n        payload_duplicate = {\n            'login': login,\n            'password': generate_random_string(10),\n            'firstName': generate_random_string(10)\n        }\n        response_duplicate = requests.post(Urls.url_courier, data=payload_duplicate)\n    \n        assert response_duplicate.status_code == 409, f\"Unexpected status code: {response_duplicate.status_code}\"\n>       assert response_duplicate.json() == {'message': \"Этот логин уже используется\"}, f\"Unexpected response: {response_duplicate.json()}\"\nE       AssertionError: Unexpected response: {'code': 409, 'message': 'Этот логин уже используется. Попробуйте другой.'}\nE       assert {'code': 409,...уйте другой.'} == {'message': '...используется'}\nE         \nE         Differing items:\nE         {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\nE         Left contains 1 more item:\nE         {'code': 409}\nE         Use -v to get more diff\n\ntests\\test_courier_create.py:31: AssertionError"}, "description": "Создание дубликата карточки. Код ответа 409 Сonflict. тело ответа Этот логин уже используется", "start": 1744268491520, "stop": 1744268491619, "uuid": "03d7a27a-fee8-4065-a315-175af0900e40", "historyId": "f9a33412c9cf9428ce7a4a7e2247dbba", "testCaseId": "f9a33412c9cf9428ce7a4a7e2247dbba", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_existing_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "13920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}