{"name": "Проверка ошибок аутентификации при вводе некорректных данных", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 404, 'message': 'Учетная запись не найдена'}\nassert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  Use -v to get more diff", "trace": "self = <tests.test_authorization_courier.TestCourierLogin object at 0x000001CA8F709A30>\nregister_new_courier = (<Response [201]>, {'firstName': 'tiwamaoqih', 'login': 'wbidiwpjbk', 'password': 'iwxusahejd'}, 499578), login = 'wvwzpieuir', password = 'iwxusahejd'\nmessage = 'Учетная запись не найдена'\n\n    @allure.title('Проверка ошибок аутентификации при вводе некорректных данных')\n    @allure.description('Генерация карточки курьера, попытка аутентификации с некорректным логином, паролем. Код ответа 404 Not Found')\n    @pytest.mark.parametrize(\"login, password, message\", [\n        (\"nonexistent_login\", \"valid_password\", \"Учетная запись не найдена\"),\n        (\"valid_login\", \"wrong_password\", \"Учетная запись не найдена\"),\n        (\"invalid_login\", \"invalid_password\", \"Учетная запись не найдена\")\n    ])\n    \n    def test_courier_login_invalid_credentials(self, register_new_courier, login, password, message):\n        with allure.step(\"Получить данные зарегистрированного курьера\"):\n            response, registered_payload, courier_id = register_new_courier\n    \n        with allure.step(\"Подготовить тестовые данные\"):\n            if password == \"valid_password\":\n                password = registered_payload['password']\n            if login == \"valid_login\":\n                login = registered_payload['login']\n            if login == \"nonexistent_login\":\n                login = generate_random_string(10)\n            if password == \"wrong_password\":\n                password = generate_random_string(10)\n    \n            payload = {\n                'login': login,\n                'password': password\n            }\n            allure.attach(f\"Test data - login: '{login}', password: '{password}'\", name=\"Test Parameters\")\n    \n        with allure.step(\"Отправить запрос с некорректными данными\"):\n            response = requests.post(Urls.url_courier_login, data=payload)\n            allure.attach(f\"Response: {response.text}\", name=\"Response Data\")\n    \n        with allure.step(\"Проверить статус код 404\"):\n            assert response.status_code == 404, f\"Unexpected status code: {response.status_code}\"\n    \n        with allure.step(\"Проверить сообщение об ошибке\"):\n            response_json = response.json()\n>           assert response_json == {'message': message}, f\"Unexpected response: {response_json}\"\nE           AssertionError: Unexpected response: {'code': 404, 'message': 'Учетная запись не найдена'}\nE           assert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\nE             \nE             Omitting 1 identical items, use -vv to show\nE             Left contains 1 more item:\nE             {'code': 404}\nE             Use -v to get more diff\n\ntests\\test_authorization_courier.py:109: AssertionError"}, "description": "Генерация карточки курьера, попытка аутентификации с некорректным логином, паролем. Код ответа 404 Not Found", "steps": [{"name": "Получить данные зарегистрированного курьера", "status": "passed", "start": 1744268489721, "stop": 1744268489721}, {"name": "Подготовить тестовые данные", "status": "passed", "attachments": [{"name": "Test Parameters", "source": "b2b41586-cd0f-4296-ae6d-7a48a27cd94d-attachment.attach"}], "start": 1744268489721, "stop": 1744268489723}, {"name": "Отправить запрос с некорректными данными", "status": "passed", "attachments": [{"name": "Response Data", "source": "f9582894-6a6d-44d9-a379-743c499680c0-attachment.attach"}], "start": 1744268489723, "stop": 1744268489863}, {"name": "Проверить статус код 404", "status": "passed", "start": 1744268489863, "stop": 1744268489863}, {"name": "Проверить сообщение об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response: {'code': 404, 'message': 'Учетная запись не найдена'}\nassert {'code': 404,...ь не найдена'} == {'message': '...ь не найдена'}\n  \n  Omitting 1 identical items, use -vv to show\n  Left contains 1 more item:\n  {'code': 404}\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\Aleksandra\\PycharmProjects\\Sprint_7\\tests\\test_authorization_courier.py\", line 109, in test_courier_login_invalid_credentials\n    assert response_json == {'message': message}, f\"Unexpected response: {response_json}\"\n"}, "start": 1744268489864, "stop": 1744268489866}], "parameters": [{"name": "login", "value": "'nonexistent_login'"}, {"name": "password", "value": "'valid_password'"}, {"name": "message", "value": "'Учетная запись не найдена'"}], "start": 1744268489720, "stop": 1744268489870, "uuid": "fcb0e1ae-e511-44ad-b929-86fcaee326fd", "historyId": "e123b458b95c3dd776e610ae03404bb6", "testCaseId": "6c379c3d796935455063f7d5042fdf56", "fullName": "tests.test_authorization_courier.TestCourierLogin#test_courier_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-HIR29C3"}, {"name": "thread", "value": "13920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier"}]}